# Generated by Django 5.2.4 on 2025-07-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='assets/favicon/%Y/%m'),
        ),
    ]
